<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in ContactUpdateInput.php.

namespace FA\GraphQL\Type\Contact\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\Type;

abstract class ContactUpdateInputBase extends InputObjectType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('ContactUpdateInput')->setFields($this->fields())->build()
        );
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('ref', Type::string())->build(),
            FieldBuilder::create('name', Type::string())->build(),
            FieldBuilder::create('name2', Type::string())->build(),
            FieldBuilder::create('address', Type::string())->build(),
            FieldBuilder::create('phone', Type::string())->build(),
            FieldBuilder::create('phone2', Type::string())->build(),
            FieldBuilder::create('fax', Type::string())->build(),
            FieldBuilder::create('email', Type::string())->build(),
            FieldBuilder::create('lang', Type::string())->build(),
            FieldBuilder::create('notes', Type::string())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
