<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in SalesOrderLineType.php.

namespace FA\GraphQL\Type\SalesOrderLine\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\SalesOrderLineModel;

abstract class SalesOrderLineTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('SalesOrderLineType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return SalesOrderLineModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('orderId', Type::id())->build(),
            FieldBuilder::create('transType', Type::int())->build(),
            FieldBuilder::create('stockId', Type::id())->build(),
            FieldBuilder::create('description', Type::string())->build(),
            FieldBuilder::create('qtyDelivered', Type::float())->build(),
            FieldBuilder::create('unitPrice', Type::float())->build(),
            FieldBuilder::create('quantity', Type::float())->build(),
            FieldBuilder::create('qtyInvoiced', Type::float())->build(),
            FieldBuilder::create('discountPercent', Type::float())->build(),
        ];
    }
}
