<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in SalesAreaType.php.

namespace FA\GraphQL\Type\SalesArea\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\SalesAreaModel;

abstract class SalesAreaTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('SalesAreaType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return SalesAreaModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('name', Type::string())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
