<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in SalesOrderUpdateInput.php.

namespace FA\GraphQL\Type\SalesOrder\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\Type;

abstract class SalesOrderUpdateInputBase extends InputObjectType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('SalesOrderUpdateInput')->setFields($this->fields())->build()
        );
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('transType', Type::int())->build(),
            FieldBuilder::create('version', Type::int())->build(),
            FieldBuilder::create('template', Type::boolean())->build(),
            FieldBuilder::create('customerId', Type::id())->build(),
            FieldBuilder::create('branchId', Type::id())->build(),
            FieldBuilder::create('reference', Type::string())->build(),
            FieldBuilder::create('customerRef', Type::string())->build(),
            FieldBuilder::create('comments', Type::string())->build(),
            FieldBuilder::create('orderDate', \Anorm\GraphQL\Type\DateType::instance())->build(),
            FieldBuilder::create('salesTypeId', Type::id())->build(),
            FieldBuilder::create('shipperId', Type::id())->build(),
            FieldBuilder::create('deliveryAddress', Type::string())->build(),
            FieldBuilder::create('phone', Type::string())->build(),
            FieldBuilder::create('email', Type::string())->build(),
            FieldBuilder::create('deliverTo', Type::string())->build(),
            FieldBuilder::create('freight', Type::float())->build(),
            FieldBuilder::create('locationId', Type::id())->build(),
            FieldBuilder::create('deliveryDate', \Anorm\GraphQL\Type\DateType::instance())->build(),
            FieldBuilder::create('paymentTermsId', Type::id())->build(),
            FieldBuilder::create('total', Type::float())->build(),
            FieldBuilder::create('prepaymentAmount', Type::float())->build(),
            FieldBuilder::create('allocated', Type::float())->build(),
        ];
    }
}
