<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in CustomerType.php.

namespace FA\GraphQL\Type\Customer\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\CustomerModel;

abstract class CustomerTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('CustomerType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return CustomerModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('name', Type::string())->build(),
            FieldBuilder::create('ref', Type::string())->build(),
            FieldBuilder::create('address', Type::string())->build(),
            FieldBuilder::create('taxId', Type::id())->build(),
            FieldBuilder::create('currencyId', Type::id())->build(),
            FieldBuilder::create('salesTypeId', Type::id())->build(),
            FieldBuilder::create('creditStatusId', Type::id())->build(),
            FieldBuilder::create('paymentTermsId', Type::id())->build(),
            FieldBuilder::create('discountPercent', Type::float())->build(),
            FieldBuilder::create('paymentDiscountPercent', Type::float())->build(),
            FieldBuilder::create('creditLimit', Type::float())->build(),
            FieldBuilder::create('notes', Type::string())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
