<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in LocationType.php.

namespace FA\GraphQL\Type\Location\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\LocationModel;

abstract class LocationTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('LocationType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return LocationModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('name', Type::string())->build(),
            FieldBuilder::create('deliveryAddress', Type::string())->build(),
            FieldBuilder::create('phone', Type::string())->build(),
            FieldBuilder::create('phone2', Type::string())->build(),
            FieldBuilder::create('fax', Type::string())->build(),
            FieldBuilder::create('email', Type::string())->build(),
            FieldBuilder::create('contact', Type::string())->build(),
            FieldBuilder::create('fixedAsset', Type::boolean())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
