<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in BranchUpdateInput.php.

namespace FA\GraphQL\Type\Branch\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\Type;

abstract class BranchUpdateInputBase extends InputObjectType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('BranchUpdateInput')->setFields($this->fields())->build()
        );
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('customerId', Type::id())->build(),
            FieldBuilder::create('name', Type::string())->build(),
            FieldBuilder::create('ref', Type::string())->build(),
            FieldBuilder::create('address', Type::string())->build(),
            FieldBuilder::create('postAddress', Type::string())->build(),
            FieldBuilder::create('salesmanId', Type::id())->build(),
            FieldBuilder::create('salesAreaId', Type::id())->build(),
            FieldBuilder::create('taxGroupId', Type::id())->build(),
            FieldBuilder::create('locationId', Type::id())->build(),
            FieldBuilder::create('shipperId', Type::id())->build(),
            FieldBuilder::create('notes', Type::string())->build(),
            FieldBuilder::create('bankAccount', Type::string())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
