#!/bin/sh
# sendmail_path for the GraphQL module's test stack. PHP's mail() pipes the whole
# message (To:, Subject:, headers, body) here instead of to a mail transport; it is
# kept as one .eml file, which the tests and `docker/fa-graphql mail` read. PHP
# passes its own -t -i style arguments on some builds; they are ignored.
set -eu
umask 000
dir=/var/mail-catcher
name="$(date +%Y%m%d%H%M%S)-$$-$(od -An -N4 -tx4 /dev/urandom | tr -d ' \n')"
cat > "$dir/.$name.tmp"
mv "$dir/.$name.tmp" "$dir/$name.eml"
