<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in AllocationType.php.

namespace FA\GraphQL\Type\Allocation\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\AllocationModel;

abstract class AllocationTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('AllocationType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return AllocationModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('customerId', Type::id())->build(),
            FieldBuilder::create('amount', Type::float())->build(),
            FieldBuilder::create('date', \Anorm\GraphQL\Type\DateType::instance())->build(),
            FieldBuilder::create('fromType', Type::int())->build(),
            FieldBuilder::create('fromId', Type::id())->build(),
            FieldBuilder::create('toType', Type::int())->build(),
            FieldBuilder::create('toId', Type::id())->build(),
        ];
    }
}
