<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in PaymentTermsType.php.

namespace FA\GraphQL\Type\PaymentTerms\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\PaymentTermsModel;

abstract class PaymentTermsTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('PaymentTermsType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return PaymentTermsModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('name', Type::string())->build(),
            FieldBuilder::create('daysBeforeDue', Type::int())->build(),
            FieldBuilder::create('dayInFollowingMonth', Type::int())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
