<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in InvoiceLineType.php.

namespace FA\GraphQL\Type\InvoiceLine\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\InvoiceLineModel;

abstract class InvoiceLineTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('InvoiceLineType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return InvoiceLineModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('invoiceId', Type::id())->build(),
            FieldBuilder::create('transType', Type::int())->build(),
            FieldBuilder::create('deliveryLineId', Type::id())->build(),
            FieldBuilder::create('stockId', Type::id())->build(),
            FieldBuilder::create('description', Type::string())->build(),
            FieldBuilder::create('unitPrice', Type::float())->build(),
            FieldBuilder::create('unitTax', Type::float())->build(),
            FieldBuilder::create('quantity', Type::float())->build(),
            FieldBuilder::create('discountPercent', Type::float())->build(),
            FieldBuilder::create('standardCost', Type::float())->build(),
            FieldBuilder::create('qtyCredited', Type::float())->build(),
        ];
    }
}
