<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in InvoiceCreateInput.php.

namespace FA\GraphQL\Type\Invoice\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\Type;

abstract class InvoiceCreateInputBase extends InputObjectType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('InvoiceCreateInput')->setFields($this->fields())->build()
        );
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('transType', Type::int())->build(),
            FieldBuilder::create('version', Type::int())->build(),
            FieldBuilder::create('customerId', Type::id())->build(),
            FieldBuilder::create('branchId', Type::id())->build(),
            FieldBuilder::create('date', Type::nonNull(\Anorm\GraphQL\Type\DateType::instance()))->build(),
            FieldBuilder::create('dueDate', \Anorm\GraphQL\Type\DateType::instance())->build(),
            FieldBuilder::create('reference', Type::string())->build(),
            FieldBuilder::create('salesTypeId', Type::id())->build(),
            FieldBuilder::create('orderId', Type::id())->build(),
            FieldBuilder::create('amount', Type::float())->build(),
            FieldBuilder::create('tax', Type::float())->build(),
            FieldBuilder::create('freight', Type::float())->build(),
            FieldBuilder::create('freightTax', Type::float())->build(),
            FieldBuilder::create('discount', Type::float())->build(),
            FieldBuilder::create('allocated', Type::float())->build(),
            FieldBuilder::create('prepaymentAmount', Type::float())->build(),
            FieldBuilder::create('rate', Type::float())->build(),
            FieldBuilder::create('shipperId', Type::id())->build(),
            FieldBuilder::create('paymentTermsId', Type::id())->build(),
            FieldBuilder::create('taxIncluded', Type::boolean())->build(),
        ];
    }
}
