<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in StockItemType.php.

namespace FA\GraphQL\Type\StockItem\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\StockItemModel;

abstract class StockItemTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('StockItemType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return StockItemModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('categoryId', Type::id())->build(),
            FieldBuilder::create('taxTypeId', Type::id())->build(),
            FieldBuilder::create('description', Type::string())->build(),
            FieldBuilder::create('longDescription', Type::string())->build(),
            FieldBuilder::create('units', Type::string())->build(),
            FieldBuilder::create('mbFlag', Type::string())->build(),
            FieldBuilder::create('editable', Type::boolean())->build(),
            FieldBuilder::create('noSale', Type::boolean())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
