<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in SalesTypeType.php.

namespace FA\GraphQL\Type\SalesType\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\SalesTypeModel;

abstract class SalesTypeTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('SalesTypeType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return SalesTypeModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('name', Type::string())->build(),
            FieldBuilder::create('taxIncluded', Type::boolean())->build(),
            FieldBuilder::create('factor', Type::float())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
