<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in DeliveryLineUpdateInput.php.

namespace FA\GraphQL\Type\DeliveryLine\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\Type;

abstract class DeliveryLineUpdateInputBase extends InputObjectType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('DeliveryLineUpdateInput')->setFields($this->fields())->build()
        );
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('deliveryId', Type::id())->build(),
            FieldBuilder::create('transType', Type::int())->build(),
            FieldBuilder::create('stockId', Type::id())->build(),
            FieldBuilder::create('description', Type::string())->build(),
            FieldBuilder::create('unitPrice', Type::float())->build(),
            FieldBuilder::create('unitTax', Type::float())->build(),
            FieldBuilder::create('quantity', Type::float())->build(),
            FieldBuilder::create('discountPercent', Type::float())->build(),
            FieldBuilder::create('standardCost', Type::float())->build(),
            FieldBuilder::create('qtyInvoiced', Type::float())->build(),
            FieldBuilder::create('orderLineId', Type::id())->build(),
        ];
    }
}
