<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in CurrencyType.php.

namespace FA\GraphQL\Type\Currency\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\CurrencyModel;

abstract class CurrencyTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('CurrencyType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return CurrencyModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('name', Type::string())->build(),
            FieldBuilder::create('symbol', Type::string())->build(),
            FieldBuilder::create('country', Type::string())->build(),
            FieldBuilder::create('hundredsName', Type::string())->build(),
            FieldBuilder::create('autoUpdate', Type::boolean())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
