<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in BankAccountType.php.

namespace FA\GraphQL\Type\BankAccount\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\BankAccountModel;

abstract class BankAccountTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('BankAccountType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return BankAccountModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('glAccountId', Type::id())->build(),
            FieldBuilder::create('accountType', Type::int())->build(),
            FieldBuilder::create('name', Type::string())->build(),
            FieldBuilder::create('number', Type::string())->build(),
            FieldBuilder::create('bankName', Type::string())->build(),
            FieldBuilder::create('bankAddress', Type::string())->build(),
            FieldBuilder::create('currencyId', Type::id())->build(),
            FieldBuilder::create('defaultForCurrency', Type::boolean())->build(),
            FieldBuilder::create('chargeAccountId', Type::id())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
