<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in SalesmanType.php.

namespace FA\GraphQL\Type\Salesman\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\SalesmanModel;

abstract class SalesmanTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('SalesmanType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return SalesmanModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('name', Type::string())->build(),
            FieldBuilder::create('phone', Type::string())->build(),
            FieldBuilder::create('fax', Type::string())->build(),
            FieldBuilder::create('email', Type::string())->build(),
            FieldBuilder::create('provision', Type::float())->build(),
            FieldBuilder::create('breakPoint', Type::float())->build(),
            FieldBuilder::create('provision2', Type::float())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
