<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in CustomerPaymentType.php.

namespace FA\GraphQL\Type\CustomerPayment\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\CustomerPaymentModel;

abstract class CustomerPaymentTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('CustomerPaymentType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return CustomerPaymentModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('transType', Type::int())->build(),
            FieldBuilder::create('version', Type::int())->build(),
            FieldBuilder::create('customerId', Type::id())->build(),
            FieldBuilder::create('branchId', Type::id())->build(),
            FieldBuilder::create('date', \Anorm\GraphQL\Type\DateType::instance())->build(),
            FieldBuilder::create('reference', Type::string())->build(),
            FieldBuilder::create('amount', Type::float())->build(),
            FieldBuilder::create('discount', Type::float())->build(),
            FieldBuilder::create('allocated', Type::float())->build(),
            FieldBuilder::create('rate', Type::float())->build(),
        ];
    }
}
