<?php

// GENERATED by anorm-graphql — do not edit. Changes belong in CreditStatusType.php.

namespace FA\GraphQL\Type\CreditStatus\Base;

use Anorm\GraphQL\Builder\FieldBuilder;
use Anorm\GraphQL\Builder\ObjectBuilder;
use GraphQL\Type\Definition\Type;
use FA\GraphQL\Model\CreditStatusModel;

abstract class CreditStatusTypeBase extends \FA\GraphQL\Type\FaModelType
{
    public function __construct()
    {
        parent::__construct(
            ObjectBuilder::create('CreditStatusType')->setFields($this->fields())->build()
        );
    }

    protected function modelClass(): string
    {
        return CreditStatusModel::class;
    }

    protected function fields(): array
    {
        return [
            FieldBuilder::create('id', Type::nonNull(Type::id()))->build(),
            FieldBuilder::create('description', Type::string())->build(),
            FieldBuilder::create('disallowInvoices', Type::boolean())->build(),
            FieldBuilder::create('inactive', Type::boolean())->build(),
        ];
    }
}
